import type { Metadata } from "next";
import "./globals.css";
import { Oswald } from 'next/font/google'

const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald',
});


export const metadata: Metadata = {
  title: "Expense App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${oswald.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
